package com.me.silencedut.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.me.silencedut.greendao.GreenNews;

import com.me.silencedut.greendao.GreenNewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenNewsDaoConfig;

    private final GreenNewsDao greenNewsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenNewsDaoConfig = daoConfigMap.get(GreenNewsDao.class).clone();
        greenNewsDaoConfig.initIdentityScope(type);

        greenNewsDao = new GreenNewsDao(greenNewsDaoConfig, this);

        registerDao(GreenNews.class, greenNewsDao);
    }
    
    public void clear() {
        greenNewsDaoConfig.getIdentityScope().clear();
    }

    public GreenNewsDao getGreenNewsDao() {
        return greenNewsDao;
    }

}
