package com.me.silencedut.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_STAT".
*/
public class GreenStatDao extends AbstractDao<GreenStat, Long> {

    public static final String TABLENAME = "GREEN_STAT";

    /**
     * Properties of entity GreenStat.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Statentity = new Property(1, String.class, "statentity", false, "STATENTITY");
        public final static Property Statkind = new Property(2, String.class, "statkind", false, "STATKIND");
    };


    public GreenStatDao(DaoConfig config) {
        super(config);
    }
    
    public GreenStatDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_STAT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STATENTITY\" TEXT," + // 1: statentity
                "\"STATKIND\" TEXT);"); // 2: statkind
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_STAT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GreenStat entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String statentity = entity.getStatentity();
        if (statentity != null) {
            stmt.bindString(2, statentity);
        }
 
        String statkind = entity.getStatkind();
        if (statkind != null) {
            stmt.bindString(3, statkind);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GreenStat readEntity(Cursor cursor, int offset) {
        GreenStat entity = new GreenStat( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // statentity
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // statkind
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GreenStat entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStatentity(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStatkind(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GreenStat entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GreenStat entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
